# Generated by Django 6.0.3 on 2026-03-06 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "1-10", "11-50", "51-200"',
                        max_length=50,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                (
                    "billing_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tag strings"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin-only notes")),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["account_status"], name="companies_c_account_345adb_idx"
                    )
                ],
            },
        ),
    ]
