# Generated by Django 6.0.3 on 2026-03-06 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(max_length=255)),
                ("avatar_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("role_name", models.CharField(default="MEMBER", max_length=50)),
                ("role_level", models.IntegerField(default=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("notification_email", models.BooleanField(default=True)),
                ("notification_in_app", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_profiles",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="users_userp_company_1d12ff_idx"
                    ),
                    models.Index(
                        fields=["role_level"], name="users_userp_role_le_beeb28_idx"
                    ),
                    models.Index(fields=["email"], name="users_userp_email_98de9a_idx"),
                ],
            },
        ),
    ]
